[zh-tw]
  title = "毛哥EM資訊密技"
  LanguageName = "繁體中文"
  weight = 1

[en]
  title = "EM's Tec Secret" # just for the sake of showing this is possible
  LanguageName = "English(Not Updating)"
  weight = 2
