[[main]]
  name = "首頁"
  url = ""
  weight = -110

[[main]]
  name = "關於"
  url = "about/"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "相關連結"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "本站Github"
  url = "https://www.linkedin.com/"
[[main]]
  parent = "Links"
  name = "官方IG"
  url = "https://www.instagram.com/em.tec.blog/"

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/Edit-Mr/"
[[social]]
  name = "instagram"
  weight = 2
  url = "https://www.instagram.com/elvisdragonmao/"
[[social]]
  name = "rss"
  weight = 3
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
